// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqbbamdfmjzfxctgfvid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYmJhbWRmbWp6ZnhjdGdmdmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjExNTcsImV4cCI6MjA1OTMzNzE1N30.I9fROGD1TDUApQcLQW6LM6Qv16nzdw0GHO0Vyi1OeEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);